list/urls.py
from django.urls import path

from list.views import (
    IndexView,
    TaskCreateView,
    TaskUpdateView,
    TakDeleteView,
    TaskUpdateDoneView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

app_name = "list"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("task-create/", TaskCreateView.as_view(), name="create-task"),
    path("task-update/<int:pk>/", TaskUpdateView.as_view(), name="update-task"),
    path("task-delete/<int:pk>/", TakDeleteView.as_view(), name="delete-task"),
    path("task-update-done/<int:pk>/", TaskUpdateDoneView.as_view(), name="update-task-done"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

py_todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("list.urls", namespace="list"))
]

list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(
        null=True,
        blank=True
    )
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="task")

    class Meta:
        ordering = ["is_done"]

    def __str__(self):
        return f"{self.content}"

list/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View, generic

from list.models import Task, Tag


class IndexView(generic.ListView):
    model = Task
    template_name = "list/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("list:index")


class TakDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("list:index")


class TaskUpdateDoneView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)

        # Update the 'done' field
        task.is_done = not task.is_done
        task.save()

        return redirect(reverse("list:index"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Todo list</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
  {% block sidebar %}
    {% include "includes/sidebar.html" %}
  {% endblock %}

  {% block content %}

  {% endblock %}
</body>
</html>

templates/includes/sidebar.html
<ul>
  <li><a href="{% url 'list:index' %}">Home</a></li>
  <li><a href="{% url 'list:tag-list' %}">Tags</a></li>
</ul>

templates/list/index.html
{% extends "base.html" %}

{% block content %}
  <h1 class="text-center">TODO LIST
    <a href="{% url 'list:create-task' %}" class="btn btn-success">Create task</a>
  </h1>


<ul class="list-group">
  {% for task in task_list %}
    <li class="list-group-item">Content: {{ task.content }} <br>
      Is done: {{ task.is_done }}
        <form method="post" action="{% url 'list:update-task-done' pk=task.id %}">
      {% csrf_token %}
      <input type="hidden" name="task_id" value="{{ task.id }}">
      <button type="submit" class="btn btn-warning">
        {% if task.is_done %}
          Complete
          {% else %}
          Undo
        {% endif %}
           </button><br>
      Created time: {{ task.created_at }} <br>Deadline: {{ task.deadline }} <br>
      {% if task.tags %}
        <span>Tags:</span>
        {% for tag in task.tags.all  %}
          <span>{{ tag }} </span>
        {% endfor %}
      {% else %}
        <p>There are no tags for this task</p>
      {% endif %}
      <a href="{% url 'list:update-task' pk=task.id %}" class="btn btn-primary">Update</a>
      <a href="{% url 'list:delete-task' pk=task.id %}" class="btn btn-danger">Delete</a>
    </li>

  {% endfor %}
</ul>

{% endblock %}

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-6">
    <div class="row">
      <div class="col-12">
          <h1 class="text-center">Delete tag?</h1>
          <form action="" method="post" class="text-center">
            {% csrf_token %}
            <input type="submit" value="Yes" class="btn btn-danger">
          </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="container mt-6">
    <div class="row">
      <div class="col-12">
        <h1 class="text-center">{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Submit">
  </form>
      </div>
    </div>
  </div>


{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="text-center">TAGS
    <a href="{% url 'list:tag-create' %}" class="btn btn-success">CREATE</a>
  </h1>

           {% if tag_list %}
              <table class="table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  {% for tag in tag_list %}
                    <tr>
                      <td>{{ tag.id }}</td>
                      <td>{{ tag.name }}</td>
                      <td><a class="btn btn-primary" href="{% url 'list:tag-update' pk=tag.id %}">UPDATE</a></td>
                      <td><a class="btn btn-danger" href="{% url 'list:tag-delete' pk=tag.id %}">DELETE</a></td>
                      <td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% else %}
              <p>There are no tags.</p>
            {% endif %}
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-6">
    <div class="row">
      <div class="col-12">
          <h1 class="text-center">Delete task?</h1>
          <form action="" method="post" class="text-center">
            {% csrf_token %}
            <input type="submit" value="Yes" class="btn btn-danger">
          </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="container mt-6">
    <div class="row">
      <div class="col-12">
        <h1 class="text-center">{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Submit">
  </form>
      </div>
    </div>
  </div>


{% endblock %}